repos:
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        args: ["--line-length", "88"]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.12.0"
    hooks:
      - id: ruff
        args: ["--fix"]  # or omit --fix to only warn

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black"]

# to run: poetry run pre-commit install
