version: 1

formatters:
  simple:
    format: "%(asctime)s %(levelname)s %(name)s: %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    formatter: simple
    level: INFO

  file:
    class: logging.handlers.RotatingFileHandler
    formatter: simple
    level: DEBUG
    filename: logs/autocompleter.log
    maxBytes: 1048576      # 1 MB
    backupCount: 5

loggers:
  intelligent_autocompleter:
    level: DEBUG
    handlers: [console, file]
    propagate: no

root:
  level: INFO
  handlers: [console]

